### ISSUE TITLE
Bug where all storage units can’t be opened.

### ISSUE THREAD

**Issue by moisterrific** [Zaicon/InfiniteChestsV3#7]
Issue: after joining the server, no storage units (chest/barrel/trash/etc.) can be opened. Hovering over them all show a name of “Chest” even for barrels and trash cans that have never been renamed.

Placing a new chest works, and the chest can be opened afterwards. All the commands seems to be working as intended, but once the player leave the server and re-connect, the newly placed chest will have buggy behavior exactly like the ones described above. 

No error messages seen in server console or the logs. 

I am using TShock 4.3.26, with this plugin compiled from source code after fixing some outdated dependencies.  

Edit:
- the bugged chests/barrels/dressers/trash cans, etc. still have the issue even after removing the plugin

**Comment by Justsomeotakuu** [comment]
I have this problem too, did you find a solution?
