### ISSUE TITLE
NPE on latest TShock Version

### ISSUE THREAD

**Issue by Stellrow** [Zaicon/InfiniteChestsV3#8]
`"exception": {
    "message": "Object reference not set to an instance of an object",
    "type": "NullReferenceException",
    "trace": "  at InfiniteChestsV3.InfChest.ItemsToString () [0x00021] in <30047d7537194e36abb8a3ffc7397560>:0 \n  at InfiniteChestsV3.DB.AddChest (InfiniteChestsV3.InfChest chest) [0x00000] in <30047d7537194e36abb8a3ffc7397560>:0 \n  at InfiniteChestsV3.InfMain.InnerConvChests () [0x00063] in <30047d7537194e36abb8a3ffc7397560>:0 \n  at InfiniteChestsV3.InfMain.<OnWorldLoadAsync>b__18_0 () [0x00006] in <30047d7537194e36abb8a3ffc7397560>:0 \n  at System.Threading.Tasks.Task.InnerInvoke () [0x00012] in <8f2c484307284b51944a1a13a14c0266>:0 \n  at System.Threading.Tasks.Task.Execute () [0x00016] in <8f2c484307284b51944a1a13a14c0266>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <8f2c484307284b51944a1a13a14c0266>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0004e] in <8f2c484307284b51944a1a13a14c0266>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in <8f2c484307284b51944a1a13a14c0266>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in <8f2c484307284b51944a1a13a14c0266>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <8f2c484307284b51944a1a13a14c0266>:0 \n  at InfiniteChestsV3.InfMain+<OnWorldLoadAsync>d__18.MoveNext () [0x00072] in <30047d7537194e36abb8a3ffc7397560>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <8f2c484307284b51944a1a13a14c0266>:0 \n  at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>m__1 (System.Object state) [0x00000] in <8f2c484307284b51944a1a13a14c0266>:0 \n  at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context (System.Object state) [0x0000e] in <8f2c484307284b51944a1a13a14c0266>:0 \n  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x0008d] in <8f2c484307284b51944a1a13a14c0266>:0 \n  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <8f2c484307284b51944a1a13a14c0266>:0 \n  at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x0002a] in <8f2c484307284b51944a1a13a14c0266>:0 \n  at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00096] in <8f2c484307284b51944a1a13a14c0266>:0 \n  at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in <8f2c484307284b51944a1a13a14c0266>:0 ",
    "inner": null
  }`

**Comment by Zaicon** [comment]
Please open a new issue with details if this happens in 1.4 as well
